
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: toy_app3_development

test:
  <<: *default
  database: toy_app3_test

staging:
  <<: *default
  database: toy_app3_staging
  
production:
  <<: *default
  database: toy_app3_production
  username: toy_app3
  password: <%= ENV['TOY_APP3_DATABASE_PASSWORD'] %>
