# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fec88ff39ec3986edaaf1d8265dd63b99653c45c74297f527df04a4e278887760fe56aede34df63375c8edbf29401e0cc7c4e1f2957c77ad4a3ef694d07c723e

test:
  secret_key_base: 73683fa70abb9cb7ed6d7ff1c31f53f9114f5e635a4ae8bcfca2245f031fe3de8629550b742988dc042840085f6cb6b4e7f06d41fed655a8da8a88953d0abff2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
